### ISSUE TITLE
app is failing after dart2js

### ISSUE THREAD

**Issue by isoos** [isoos/pwa#10]
Original report:
https://github.com/isoos/pwa/issues/9#issuecomment-308546103

This turned out really weird. I've changed its `main.dart` to this, and it still fails.

```
void main() {
  print(pwa.Client);
  bootstrap(AppComponent, [
  //  new Provider(pwa.Client, useValue: new pwa.Client()),
  ]);
}
```

With the above change, none of the `pwa` code get executed, no SW registered, only the compiled JS should get larger (the compiled `pwa` and the `service_worker` library).

Yet, I see the exception too:
```
html_dart2js.dart:3558 EXCEPTION: NoSuchMethodError: method not found: '$index' (J.getInterceptor$asx(...).$index is not a function)
STACKTRACE: 
TypeError: J.getInterceptor$asx(...).$index is not a function
    at Object.J.$index$asx (http://localhost:8000/main.dart.js:56519:43)
    at Object.LatLng$ (http://localhost:8000/main.dart.js:53477:66)
    at ViewAppComponentHost0.detectChangesInternal$0 (http://localhost:8000/main.dart.js:55817:20)
    at ViewAppComponentHost0.detectCrash$0 (http://localhost:8000/main.dart.js:24924:16)
    at ViewAppComponentHost0.dart.AppView.detectChanges$0 (http://localhost:8000/main.dart.js:24912:16)
    at ApplicationRefImpl._runTickGuarded$0 (http://localhost:8000/main.dart.js:22344:16)
    at ApplicationRefImpl.tick$0 (http://localhost:8000/main.dart.js:22319:16)
    at ApplicationRefImpl._loadComponent$1 (http://localhost:8000/main.dart.js:22296:14)
    at ApplicationRefImpl_bootstrap_closure.call$0 (http://localhost:8000/main.dart.js:22511:12)
    at ApplicationRefImpl_run_closure.dart.ApplicationRefImpl_run_closure.call$0 (http://localhost:8000/main.dart.js:22451:34)
ORIGINAL EXCEPTION: NoSuchMethodError: method not found: '$index' (J.getInterceptor$asx(...).$index is not a function)
```

I suspect this may be related to https://github.com/isoos/service_worker/issues/6

**Comment by isoos** [comment]
Fixing the dart2js warning didn't fixed this issue. Investigating.

**Comment by erikist** [comment]
Awesome, thanks! I will keep my eyes open and watching.

**Comment by isoos** [comment]
The core issue seems to be that `package:js_wrapping` (used by `package:google_maps`) is using `dart:js`, which predates and is unfortunately not compatible with `package:js` (used by `service_worker` and `pwa`). (/ping @jacob314 to confirm that the error above may be coming because of this). 

Pinging @a14n: Do you have any plans to migrate `js_wrapping` from `dart:js` and use `package:js` instead?

**Comment by a14n** [comment]
Do you have a repo I can use to reproduce the issue ?

**Comment by isoos** [comment]
@a14n: yeah, this: https://github.com/erikist/pwa_google_maps

**Comment by a14n** [comment]
I took a look and tried to reduce the issue.

If I start with the [map-simple example](https://github.com/a14n/dart-google-maps/tree/master/example/01-basics/map-simple) and I only add the following **used** import (`service_worker: ^0.0.15`) to `page.dart` then an error occurs and nothing works.

```dart
import 'package:service_worker/window.dart';
```

It looks like an issue in `dart2js` to me. (/cc @sigmundch)

**Comment by a14n** [comment]
Same issue in dartium.
I made the tests with sdk-1.22.x and sdk-1.23.x.

I also made a quick test without `service_worker` but with `package:js` but I don't see the error. It looks like something in parsing `service_worker` triggers the error but I haven't found what for now.

**Comment by a14n** [comment]
I have a really simple repro I will use to submit an issue against SDK. Basically the error occurs when you use both `dart:js` and a `package:js` facade extending the `dart:html#Event`.

**Comment by isoos** [comment]
Interesting, thanks for looking into it! And `service_worker` does implement `Event` in a few places... Presumably, if I remove the `Event` interface (but keep the methods), it won't break much of the users, but keeps compatibility... Am I right with that?

**Comment by a14n** [comment]
It's worth a try and see if it is the only case that triggers the error.

**Comment by sigmundch** [comment]
sorry for the slow response, but indeed I was wondering if it was a js-interop issue that is not dart2js specific. Thanks for investigating @a14n!

**Comment by isoos** [comment]
Just found out about this, could be related: https://github.com/dart-lang/sdk/issues/27926

**Comment by isoos** [comment]
@a14n: thanks for the lead on `dart:html#Event`, indeed, it was the issue.

@erikist: I've published a new version of `service_worker`, if you upgrade your dependencies, it should be working with google maps (and other JS-based libs). Please let me know if the issue comes up again.
