### ISSUE TITLE
Any further work on this?  I can't get it to work...

### ISSUE THREAD

**Issue by rickbsgu** [isoos/pwa#15]
Two examples I tried ('additional_offline_urls' and 'pwa_defaults') didn't work at all.  I updated 'pwa_defaults' to angular 4  just for grins & that doesn't work either.

This is the determining factor whether I use Dart or go back to JS.  Next project needs to be a pwa...

If we _can_ get this to work, the examples should be updated to a4.

**Comment by isoos** [comment]
Hi @rickbsgu,

I'm sorry, the library is a bit behind, I haven't tracked the recent angular changes, but I hope I'll soon have some time to make sure it works well.

Could you please share what kind of features or which platform you consider crucial?

**Comment by rickbsgu** [comment]
I guess the main thing is I'd like to see the examples working...  Upgrading them to A4 would be a bonus, but I can't get them to work in A2, either.  My dev environment is Mac, Dart 1.24.2, and Chrome, latest.

Do they work on your side?  Perhaps I'm not doing something correctly or don't have something set up correctly in my environment?

**Comment by kevmoo** [comment]
We have things working here - https://github.com/dart-lang/angular/tree/master/examples/hacker_news_pwa

This is with Anugalr5.

Let us know if you have any other issues.

**Comment by Aman-US-Punjabi** [comment]
When i try to use Push notification, it throws error:
dart_sdk.js:101652 EXCEPTION: No provider found for pwa.Client
STACKTRACE: 
packages/$sdk/dev_compiler/amd/dart_sdk.js 4835:29                          throw
packages/angular/src/core/change_detection/change_detection.ddc.js 2627:15  throwsNotFound
packages/angular/src/core/change_detection/change_detection.ddc.js 2250:44  get
packages/angular/src/bootstrap/modules.ddc.js 1648:33
