### ISSUE TITLE
Publish it on PWAThemes.com

### ISSUE THREAD

**Issue by cborodescu** [isoos/pwa#16]
Hi István,

This is Ciprian from PWAThemes.com - a marketplace for Progressive Web Apps. I noticed your PWA on GitHub and I wanted to ask if it would be OK with you to publish it on PWAThemes.com as a freebie, mentioning you as an author and all. 

Looking forward to hearing your thoughts.

**Comment by isoos** [comment]
It is up to you whether you publish about an open source project :)
