### ISSUE TITLE
Upgrade the sample projects

### ISSUE THREAD

**Issue by muniz95** [isoos/pwa#29]
The example projects are way outdated, using a version of Angular that doesn't exist anymore (_angular2_ package, replaced by _angular_). I did some small tests and it is possible to re-implement the basic examples (so far, I made the _pwa-default_ project work).

Addressing the issue to link with an upcoming pull request, that probably will resolve #22.

**Comment by LCostaN** [comment]
Indeed, I was about to create a issue about this myself. Besides the first example, the others are not very clear and hard to understand. I'm particularly confused about how to handle routes in my application that runs on both web and mobile.
