### ISSUE TITLE
support JSON.stringify for `PushSubscription`

### ISSUE THREAD

**Issue by zoechi** [isoos/pwa#3]
`JSON.stringify(pushSubscription)` reveals some information that is not directly available as property (key and auth) but that requires access to [_delegate](https://github.com/isoos/service_worker/blob/master/lib/src/service_worker_api.dart#L546) which is private.

It would be nice if `PushSubscription` would provide a method like `toJsonString()` like
```dart
String toJsonString() => JSON.decode(_jsonStringify(_delegate)) as Map<String, dynamic>;
```
with
```dart
@JS('JSON.stringify')
external String _jsonStringify(Object obj);
```

**Comment by isoos** [comment]
Nice hack :), and I think this will be the fallback implementation, but first, I'd like to understand what fields are there to expose that are not (yet)? Using the native access methods would be more preferable for me.

**Comment by zoechi** [comment]
There doesn't seem to be a native access method.
I got this from https://developers.google.com/web/updates/2016/03/web-push-encryption
Also in pure JS you get it only this way.

**Comment by zoechi** [comment]
Nice. I tried to find information about `getKeysAsString()` but only found https://developer.mozilla.org/en-US/docs/Web/API/PushSubscription/getKey
Where did you find about `getKeysAsString()`?

**Comment by isoos** [comment]
There is no such thing in the Push API, I've implemented it in here:
https://github.com/isoos/service_worker/commit/6a5fb0b836713f816ef6040fac01dc9f2868719d

**Comment by zoechi** [comment]
I see. I somehow got the impression that was the browser object.
Thanks for clarification.

**Comment by zoechi** [comment]
Thanks a lot for the awesome response time :+1:
