### ISSUE TITLE
FR: Generate scaffold of manifest.json

### ISSUE THREAD

**Issue by filiph** [isoos/pwa#6]
https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/

When manifest.json is there and all works, PWA shines the most.

This would involve 

* [ ] Create manifest.json from data in pubspec.yaml and with sane defaults
* [ ] (Optionally) add current `<link>` tag to index.html
* [ ] (Optionally) add theme `<meta`> tag to index.html (https://github.com/filiph/startup_namer/commit/6eb09fb4ee426028bfbab137544fce39bd0f5095)
* [ ] (Optionally) add icons so that the whole app is fully "PWA" with just one command.

See https://github.com/filiph/startup_namer/commit/168b068f255dab576cc9a2598ae007b269b8e254 for full scope of work involved.

This can take an AngularDart app to 99/100 PWA score in [Lighthouse](https://developers.google.com/web/tools/lighthouse/).

**Comment by isoos** [comment]
I've published the first version of this, but I've cut some corners:
- the code generator will give you the structure in the `manifest.json`, but the values are mock values and you need to edit for yourself
- the default theme color is white and not autodetected from the CSS styles
- the update of the `index.html` is far from elegant

Give it a try!
